# Generated by Django 5.1.2 on 2024-10-29 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_quiz_app', '0002_ckeditortoolbarsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CKEditorToolbarSettings',
        ),
    ]
